import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen h-screen p-2`}>
        <nav className="p-2 w-full flex justify-center">
          <div className="border rounded-lg px-4 py-2 text-slate-400 hover:text-black transition-all cursor-pointer">
            <Link className="" href="/">Home</Link>
          </div>
        </nav>
        {children}
        <div><Toaster position='bottom-right' /></div>
      </body>
    </html>
  );
}
